language:
  - cpp

compiler:
  - clang
  - g++

sudo:
  - false

matrix:
  include:
    # Linux {
    - os: linux
      env: BUILD_TYPE=Release
    - os: linux
      env: BUILD_TYPE=Debug
    # }

script:
  - cmake . -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -Bbuild
  - cd build
  - make
  - ./example `pwd`/libexample1.so `pwd`/libexample2.so
