language:
  - cpp

sudo:
  - false

os:
  - linux

compiler:
  - clang++
  - g++

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

script:
  - cmake . -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -Bbuild
  - cd build
  - make
  - ./example `pwd`/libexample1.so `pwd`/libexample2.so
